# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FenvFvm < Formula
  desc "FENV-compatible Flutter version management tool using FVM backend"
  homepage "https://github.com/shunirr/fenv-fvm"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.4/fenv-fvm-darwin-amd64.tar.gz"
      sha256 "a762239cb42aa88c98c2f0bb927d700df48f3258d6268af58b386d5ee752426d"

      def install
        bin.install "fenv-fvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.4/fenv-fvm-darwin-arm64.tar.gz"
      sha256 "7523c657f1f1aaacadf5e14409f2fa672a5a279a36d62002d023427315d1d496"

      def install
        bin.install "fenv-fvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.4/fenv-fvm-linux-amd64.tar.gz"
      sha256 "1cab911175698539c022e4739da5052bd1d8cdecb7d19c53f2e2af8d99ea3044"
      def install
        bin.install "fenv-fvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.4/fenv-fvm-linux-arm64.tar.gz"
      sha256 "217f6108e8a78ab69e750af7cd5fe87e29e9785b9b411783d70ea918648360cc"
      def install
        bin.install "fenv-fvm"
      end
    end
  end

  test do
    system "#{bin}/fenv-fvm", "version"
  end
end
