# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FenvFvm < Formula
  desc "FENV-compatible Flutter version management tool using FVM backend"
  homepage "https://github.com/shunirr/fenv-fvm"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.2/fenv-fvm-darwin-amd64.tar.gz"
      sha256 "624db81b31a3f17d09afa95ac45d26008802e3003b5ba895105ff8f4a61ed30f"

      def install
        bin.install "fenv-fvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.2/fenv-fvm-darwin-arm64.tar.gz"
      sha256 "3b617091479bb0117af0ebeec26b7281cf93f06b7aa5b89811bb800f4d115dda"

      def install
        bin.install "fenv-fvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.2/fenv-fvm-linux-amd64.tar.gz"
      sha256 "f85eaedd306bd4ee04d7fdfbf2c5d09ef6c32df335e9cecd220fa7c5a819c8f8"
      def install
        bin.install "fenv-fvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.2/fenv-fvm-linux-arm64.tar.gz"
      sha256 "55fb2eee4aba7f21b5e0278bb4c4048ad580a20683b459f76f3f9f81ef7cd5cc"
      def install
        bin.install "fenv-fvm"
      end
    end
  end

  test do
    system "#{bin}/fenv-fvm", "version"
  end
end
