# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FenvFvm < Formula
  desc "FENV-compatible Flutter version management tool using FVM backend"
  homepage "https://github.com/shunirr/fenv-fvm"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.5/fenv-fvm-darwin-amd64.tar.gz"
      sha256 "b6a32fdebbe4609dee8a22128277370051a027cb9b8dbcc66a6adcc8d4c0402f"

      def install
        bin.install "fenv-fvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.5/fenv-fvm-darwin-arm64.tar.gz"
      sha256 "5fd53586e7fd4d6ae97dedb46c8ea79c89498960ceb605200f2e699db90552d3"

      def install
        bin.install "fenv-fvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.5/fenv-fvm-linux-amd64.tar.gz"
      sha256 "e52a232cfdec1cbb2290c240a99dbc9486171aab7b88a220c20850949d35eb3f"
      def install
        bin.install "fenv-fvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunirr/fenv-fvm/releases/download/v0.0.5/fenv-fvm-linux-arm64.tar.gz"
      sha256 "6e6210b83e331157663e17a64f9bc86265c8594c62d45592a5f64248828d9393"
      def install
        bin.install "fenv-fvm"
      end
    end
  end

  test do
    system "#{bin}/fenv-fvm", "version"
  end
end
